ngpus: 1
tokens: 4
training:
  batch_size: 256
  accum: 1
  n_iters: 1000000
  snapshot_freq: 50000
  log_freq: 5000
  eval_freq: 5000
  snapshot_freq_for_preemption: 10000
  weight: standard
  snapshot_sampling: true
  ema: 0.9999
data:
  train: deepstarr
  valid: deepstarr
  cache_dir: data
graph:
  type: uniform
  file: data
  report_all: false
noise:
  type: geometric
  sigma_min: 0.0001
  sigma_max: 20
sampling:
  predictor: euler
  steps: 128
  noise_removal: true
eval:
  batch_size: 256
  perplexity: false
  perplexity_batch_size: 32
optim:
  weight_decay: 0
  optimizer: AdamW
  lr: 0.0003
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-08
  warmup: 2500
  grad_clip: 1.0
model:
  name: small
  type: ddit
  hidden_size: 768
  cond_dim: 256
  length: 249
  n_blocks: 12
  n_heads: 12
  scale_by_sigma: false
  dropout: 0.1
